#!/bin/bash

set -euo pipefail

tmp_venv=tmp-dep-venv
tmp_file=require.txt.tmp

if [ -d "$tmp_venv" ]
then
	echo "Error: please delete $tmp_venv first"
	exit 1
fi

python3 -m venv "$tmp_venv"

update_requirements() {
	# shellcheck disable=SC1091,SC1090
	source "$tmp_venv/bin/activate"

	local packages=(
		twnet_parser
		pytest
		flask
		dpkt
		gunicorn
		libtw2-huffman
	)

	pip install "${packages[@]}"

	{
		printf '# generated by scripts/update_dependencies.sh\n'
		pip freeze
	} > "$tmp_file"
	mv "$tmp_file" "requirements.txt"
}

update_requirements

rm -rf "$tmp_venv"
